hospital/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    path("hospital/", views.HospitalView.as_view(), name="hospitals"),
    path("hospital/<int:pk>/", views.HospitalDetailView.as_view(), name="hospital-detail"),
    path("hospital/<int:pk>/physician", views.PhysicianView.as_view(), name="hospital-physician"),
    path("physician/<int:pk>", views.PhysicianDetailView.as_view(), name="physician-detail"),
    path("physician/add", views.PhysicianCreate.as_view(), name="physician-add"),
    path("physician/<int:pk>/delete", views.PhysicianDelete.as_view(), name="physician-delete"),
    path("hospital/<int:pk>/add/", views.add_department, name="department-add"),
    path("department/", views.DepartmentView.as_view(), name="departments"),
    path("department/<int:pk>/", views.DepartmentDetailView.as_view(), name="department-detail"),
    path("department/<int:pk>/delete/", views.DepartmentDelete.as_view(), name="department-delete"),
    path("user/add/", views.UserCreate.as_view(), name="user-add"),
    path("user/<int:pk>/delete/", views.UserDelete.as_view(), name="user-delete"),
    path("patient/", views.PatientView.as_view(), name="patients"),
    path("patient/add/", views.PatientCreateView.as_view(), name="patient-add"),
    path("patient/<int:pk>/update/", views.PatientUpdate.as_view(), name="patient-update"),
    path("patient/<int:pk>/delete/", views.PatientDeleteView.as_view(), name="patient-delete"),
    path("case/add/", views.CaseCreateView.as_view(), name="case-add"),
    path("case/<int:pk>/update/", views.CaseUpdate.as_view(), name="case-update"),
    path("case/<int:pk>/delete/", views.CaseDeleteView.as_view(), name="case-delete"),
    path("treatment/", views.TreatmentView.as_view(), name="treatments"),
    path("treatment/add/", views.TreatmentCreateView.as_view(), name="treatment-add"),
    path("disease/", views.DiseaseView.as_view(), name="diseases"),
    path("disease/add/", views.DiseaseCreateView.as_view(), name="disease-add"),
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("hospital.urls")),
    path("admin/", admin.site.urls),
]

hospital/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.db.backends.mysql.base import DatabaseWrapper


class Department(models.Model):
    did = models.AutoField(primary_key=True)
    dname = models.CharField(max_length=20)
    dtel = models.CharField(max_length=13)
    hid = models.ForeignKey("Hospital", models.CASCADE, db_column="hid")

    def __str__(self):
        return self.dname

    class Meta:
        # managed = False
        db_table = "department"


class Disease(models.Model):
    deid = models.CharField(primary_key=True, max_length=6)
    dename = models.CharField(max_length=30)

    def __str__(self):
        return f"({self.deid}): {self.dename}"

    class Meta:
        # managed = False
        db_table = "disease"


class Hospital(models.Model):
    hid = models.AutoField(primary_key=True)
    hname = models.CharField(max_length=30)
    hst_address = models.CharField(max_length=30)
    hst_city = models.CharField(max_length=30)
    hstate = models.CharField(max_length=20)
    hzip = models.IntegerField()

    class Meta:
        # managed = False
        db_table = "hospital"


class Patient(models.Model):
    GENDER = [("M", "Male"), ("F", "Female"), ("U", "Unkown")]
    RACE = [
        ("ASIAN", "Asian"),
        ("HISPANIC", "Hispanic"),
        ("LATINO", "Latin American"),
        ("AFRICAN", "African American"),
        ("OTHER", "Other"),
    ]
    STATUS = [
        ("M", "Married"),
        ("S", "Single"),
        ("D", "Devoiced"),
        ("W", "Widow or widower"),
    ]
    pid = models.AutoField(primary_key=True)
    pfname = models.CharField(max_length=30)
    plname = models.CharField(max_length=20)
    pgender = models.CharField(max_length=1, choices=GENDER)
    pbd = models.DateTimeField()
    prace = models.CharField(max_length=20, blank=True, null=True, choices=RACE)
    pstatus = models.CharField(max_length=1, choices=STATUS)

    def __str__(self):
        # pylint: disable=no-member
        return f"{self.pfname.title()} {self.plname.title()}-{self.get_pgender_display()}-{self.get_prace_display()}-{self.pbd.strftime('%m/%d/%Y')}"

    class Meta:
        # managed = False
        db_table = "patient"


class PatientTreatment(models.Model):
    STATUS = [("S", "Successful"), ("R", "Repeat"), ("F", "Failed")]
    tdate = models.DateTimeField()
    tfreq = models.BigIntegerField(default=0)
    tstatus = models.CharField(max_length=1, blank=True, null=True, choices=STATUS)
    pid = models.ForeignKey(Patient, models.CASCADE, db_column="pid")
    tid = models.ForeignKey("Treatment", models.DO_NOTHING, db_column="tid")
    phid = models.ForeignKey("Physician", models.DO_NOTHING, db_column="phid")

    class Meta:
        # managed = False
        db_table = "patient_treatment"
        unique_together = (("pid", "phid", "tid", "tdate", "tfreq"),)


class Treatment(models.Model):
    TYPE = [("PHARMA", "Pharma"), ("PROCEDURE", "Procedure"), ("SURGERY", "Surgery")]
    tid = models.AutoField(primary_key=True)
    tname = models.CharField(max_length=50)
    ttype = models.CharField(max_length=10,choices=TYPE)
    deid = models.ForeignKey(Disease, models.DO_NOTHING, db_column="deid")

    def __str__(self):
        # pylint: disable=no-member
        return f"{self.tname.title()}-{self.ttype}-{self.deid}"

    class Meta:
        # managed = False
        db_table = "treatment"


class Physician(models.Model):
    phid = models.AutoField(primary_key=True)
    phfname = models.CharField(max_length=30)
    phtel = models.CharField(max_length=13)
    phspl = models.CharField(max_length=30)
    hid = models.ForeignKey(Hospital, models.CASCADE, db_column="hid")
    patient = models.ManyToManyField(
        Patient, through="PatientTreatment", related_name="physician"
    )
    treatment = models.ManyToManyField(
        Treatment, through=PatientTreatment, related_name="physician"
    )

    def __str__(self):
        # pylint: disable=no-member
        return f"{self.phfname.title()}-{self.phspl}"

    class Meta:
        # managed = False
        db_table = "physician"


class Users(models.Model):
    uid = models.AutoField(
        db_column="UID", primary_key=True
    )  # Field name made lowercase.
    ufname = models.CharField(max_length=20)
    ulname = models.CharField(max_length=20)
    urole = models.CharField(max_length=20)
    did = models.ForeignKey(Department, models.DO_NOTHING, db_column="did")

    class Meta:
        # managed = False
        db_table = "users"

hospital/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views import generic
from django.core.exceptions import PermissionDenied
from django.db.models import Count

from .models import (
    Hospital,
    Department,
    Users,
    Physician,
    Patient,
    PatientTreatment,
    Treatment,
    Disease,
)
from .form import (
    DepartmentForm,
    UserForm,
    PhysicianForm,
    PatientForm,
    PatientUpdateForm,
    PatientTreatmentForm,
    TreatmentForm,
    DiseaseForm,
    CaseUpdateForm,
)

# pylint: disable=no-member


class IndexView(generic.ListView):
    template_name = "index.html"
    context_object_name = "hospital"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Hospital.objects.all()


class HospitalView(generic.ListView):
    model = Hospital
    template_name = "hospitals.html"


class HospitalDetailView(generic.DetailView):
    model = Hospital
    template_name = "hospital.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = DepartmentForm()
        context["add_form"] = form
        return context


class DepartmentView(generic.ListView):
    model = Department
    template_name = "departments.html"


class DepartmentDetailView(generic.DetailView):
    model = Department
    template_name = "department-detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = UserForm(self.kwargs["pk"])
        context["add_form"] = form
        return context


@login_required(login_url="login")
def add_department(request, pk):
    hospital = get_object_or_404(Hospital, pk=pk)
    form = DepartmentForm(request.POST)
    if form.is_valid:
        f = form.save(commit=False)
        f.hid = hospital
        f.save()
        # check whether it's valid:
    return redirect(reverse("hospital-detail", args=(hospital.hid,)))


class PermissionMixin(object):
    def get_object(self, *args, **kwargs):
        obj = super(PermissionMixin, self).get_object(*args, **kwargs)
        if self.request.user.is_authenticated:
            self.success_url = self.request.META.get("HTTP_REFERER") or self.success_url
            return obj
        else:
            raise PermissionDenied()


class CreateViewPermissionMixin(object):
    def form_valid(self, form):
        if self.request.user.is_authenticated:
            self.success_url = self.request.META.get("HTTP_REFERER") or self.success_url
            return super(CreateViewPermissionMixin, self).form_valid(form)
        else:
            raise PermissionDenied()

    def form_invalid(self, form):
        if self.request.user.is_authenticated:
            self.success_url = self.request.META.get("HTTP_REFERER") or self.success_url
            return super(CreateViewPermissionMixin, self).form_invalid(form)
        else:
            raise PermissionDenied()


class DepartmentDelete(PermissionMixin, generic.DeleteView):
    model = Department
    success_url = reverse_lazy("hospitals")
    template_name = "department_confirm_delete.html"


class UserCreate(generic.CreateView):
    model = Users
    fields = ["ufname", "ulname", "urole", "did"]
    template_name = "user-create.html"

    def form_valid(self, form):
        self.success_url = reverse_lazy(
            "department-detail", args=(form.cleaned_data.get("did").did,)
        ) or reverse("index")
        return super(UserCreate, self).form_valid(form)


class UserDelete(PermissionMixin, generic.DeleteView):
    model = Users
    success_url = reverse_lazy("index")
    template_name = "user_confirm_delete.html"


class PhysicianView(generic.DetailView):
    model = Hospital
    template_name = "physicians.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = PhysicianForm(self.kwargs["pk"])
        context["add_form"] = form
        return context


class PhysicianCreate(generic.CreateView):
    model = Physician
    template_name = "physician-create.html"
    fields = ["phfname", "phtel", "phspl", "hid"]

    def form_valid(self, form):
        self.success_url = reverse_lazy(
            "hospital-physician", args=(form.cleaned_data.get("hid").hid,)
        ) or reverse("index")
        # print(form.cleaned_data)
        return super(PhysicianCreate, self).form_valid(form)


class PhysicianDelete(PermissionMixin, generic.DeleteView):
    model = Physician
    success_url = reverse_lazy("index")
    template_name = "physician-confirm-delete.html"


class PhysicianDetailView(generic.DetailView):
    model = Physician
    template_name = "physician-detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["unique_patients"] = (
            self.get_object().patient.values("pid").distinct().count()
        )
        context["patient_form"] = PatientForm()
        context["patienttreatment_form"] = PatientTreatmentForm(self.kwargs["pk"])
        context["treatment_form"] = TreatmentForm()
        context["disease_form"] = DiseaseForm()

        cases = []
        status = self.request.GET.get("status")
        status = {"successful": "S", "repeated": "R", "failed": "F"}.get(status, None)
        if status:
            qs = Physician.objects.get(
                pk=self.kwargs["pk"]
            ).patienttreatment_set.filter(tstatus=status)
        else:
            qs = Physician.objects.get(pk=self.kwargs["pk"]).patienttreatment_set.all()

        for i in qs:
            t = CaseUpdateForm(instance=i)
            cases.append((i, t))
        context["cases"] = cases

        return context


class PatientView(generic.ListView):
    model = Patient
    template_name = "patients.html"

    def get_context_data(self, **kwargs):
        context = super(PatientView, self).get_context_data(**kwargs)
        forms = []
        for i in context["patient_list"]:
            forms.append(PatientUpdateForm(instance=i))

        context["patient_list"] = zip(context["patient_list"], forms)
        context["patient_form"] = PatientForm()
        return context


class PatientCreateView(CreateViewPermissionMixin, generic.CreateView):
    model = Patient
    template_name = "patient-create.html"
    fields = ["pfname", "plname", "pgender", "pbd", "prace", "pstatus"]
    success_url = reverse_lazy("index")

    def get_context_data(self, **kwargs):
        context = super(PatientCreateView, self).get_context_data(**kwargs)
        # context["patient_form"] = context["form"]
        return context


class PatientUpdate(CreateViewPermissionMixin, generic.UpdateView):
    model = Patient
    form_class = PatientUpdateForm
    template_name = "create.html"

    def get_context_data(self, **kwargs):
        context = super(PatientUpdate, self).get_context_data(**kwargs)
        # context["patient_form"] = context["form"]
        context["modal"] = "patient-update-modal.html"
        return context


class PatientDeleteView(PermissionMixin, generic.DeleteView):
    model = Patient
    success_url = reverse_lazy("index")
    template_name = "patient-confirm-delete.html"


class CaseCreateView(CreateViewPermissionMixin, generic.CreateView):
    model = PatientTreatment
    template_name = "create.html"
    fields = ["pid", "tdate", "tfreq", "tstatus", "tid", "phid"]
    success_url = reverse_lazy("index")

    def get_context_data(self, **kwargs):
        context = super(CaseCreateView, self).get_context_data(**kwargs)
        # context["patient_form"] = context["form"]
        context["modal"] = "patienttreatment-create-modal.html"
        return context


class CaseUpdate(CreateViewPermissionMixin, generic.UpdateView):
    model = PatientTreatment
    form_class = CaseUpdateForm
    # fields = ["pid", "tdate", "tfreq", "tstatus", "tid"]
    template_name = "create.html"

    def get_context_data(self, **kwargs):
        context = super(CaseUpdate, self).get_context_data(**kwargs)
        # context["patient_form"] = context["form"]
        context["modal"] = "case-update-modal.html"
        return context


class CaseDeleteView(PermissionMixin, generic.DeleteView):
    model = PatientTreatment
    success_url = reverse_lazy("index")
    template_name = "patient-confirm-delete.html"


class TreatmentView(generic.ListView):
    model = Treatment
    template_name = "treatments.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["treatment_form"] = TreatmentForm()
        return context

    def get_queryset(self):
        order = self.request.GET.get("order")
        order = {"name":"tname","type": "ttype", "diease": "deid", "count": "count"}.get(order)
        if order:
            if order == "count":
                return (
                    super()
                    .get_queryset()
                    .annotate(num_diease=Count("patienttreatment"))
                    .order_by("-num_diease")
                )
            else:
                return super().get_queryset().order_by(order)
        return super().get_queryset()


class TreatmentCreateView(CreateViewPermissionMixin, generic.CreateView):
    # model = Treatment
    template_name = "create.html"
    # fields = ["tname", "ttype", "deid"]
    form_class = TreatmentForm
    success_url = reverse_lazy("index")

    def get_context_data(self, **kwargs):
        context = super(TreatmentCreateView, self).get_context_data(**kwargs)
        # context["patient_form"] = context["form"]

hospital/templates/case-update-modal.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Edit case</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
        {% if case_id %}
            <form action="{% url 'case-update' case_id %}" method="post">
        {% else %}
            <form action="" method="post">
        {% endif %}
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}

                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}
                <input type="submit" class="btn btn-primary" value="Update">
            </form>

        </div>

    </div>
</div>

hospital/templates/create.html
{% extends 'base.html' %}
{% block content %} 
{% include modal %}
{% endblock content %}

hospital/templates/department-detail.html
{% extends './base.html' %}
{% block title %} Hostpital Management System
{% endblock title %}


{% block page_title %} {{ department.dname }}{% endblock  %}


{% block page_details %}
<div class="col-md-6 offset-md-3">
  <table class="table table-borderless table-sm">
    <thead>
      <tr>
        {% block details_title %}
        <th scope="col">Telphone</th>
        <th scope="col">Hospital</th>
        {% endblock  %}
      </tr>
    </thead>
    <tbody>
      <tr>
        {% block details_content %}
        <td>{{ department.dtel }}</td>
        <td>{{ department.hid.hname }}</td>
        {% endblock  %}
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

{% block content %}


<h2> All Users</h2>
{% if department.users_set %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Role</th>
      {% if user.is_authenticated %}
      <th></th>
      {% endif %}

    </tr>
  </thead>
  <tbody>
    {% for users in department.users_set.all %}
    <tr onclick="window.location='#';">
      <th scope="row">{{forloop.counter}}</th>
      <td>{{users.ufname | title}}</td>
      <td>{{users.ulname | title}}</td>
      <td>{{users.urole | title}}</td>
      {% if user.is_authenticated %}
      <td><button type="button" class="btn btn-danger" data-toggle="modal"
          data-target="#modal_delete_{{ forloop.counter }}"><i class="fa fa-trash-o" aria-hidden="true"></i>
          Delete</button>
        <div id="modal_delete_{{ forloop.counter }}" class="modal fade" tabindex="-1" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>are you sure to delete {{users.ufname | title}} {{users.ulname | title}}?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{% url 'user-delete' users.uid %}" method="post">
                  {% csrf_token %}
                  <input type="submit" type="button" class="btn btn-danger" value="Delete" />
                </form>
              </div>
            </div>
          </div>

        </div>
      </td>
      {% endif %}

    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>No resuorce are available.</p>
{% endif %}
<a href="{% url 'hospital-detail' department.hid.hid %}" class="badge badge-info float-right">List of all
  Departments</a>
</br>

{% if user.is_authenticated %}
<button type="button" class="btn btn-success" data-toggle="modal" data-target="#addModal">
  <i class="fa fa-plus-circle"></i> Add new user
</button>
{% endif %}

<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add new user</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'user-add'%}" method="post">
          {% csrf_token %}
          {% for field in add_form %}
          <div class="form-group">
            {{ field.errors }}

            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
          </div>
          {% endfor %}
          <input type="submit" class="btn btn-primary" value="Submit">
        </form>

      </div>

    </div>
  </div>
</div>





{% endblock content %}

hospital/templates/department_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Confirmation</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>are you sure to delete {{department.dname}}?</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{% url 'department-delete' department.did %}" method="post">
                {% csrf_token %}
                <input type="submit" type="button" class="btn btn-danger" value="Delete" />
            </form>
        </div>
    </div>
</div>

{% endblock content %}

hospital/templates/departments.html
{% extends './base.html' %}
{% block title %} Hostpital Management System
{% endblock title %}

{% block content %}


{% if department_list %}

<table class="table table-hover">
    <thead>
        <tr>
            {% block details_title %}
            <th scope="col">#</th>
            <th scope="col">Department</th>
            <th scope="col">Telphone</th>
            <th scope="col">Hostpital</th>
            {% endblock  %}
        </tr>
    </thead>
    <tbody>
        {% for department in department_list  %}
        <tr onclick="window.location='{% url 'department-detail' department.did %}';">
            <th scope="row">{{forloop.counter}}</th>
            <td>{{ department.dname }}</td>
            <td>{{ department.dtel }}</td>
            <td> <a href="{% url 'hospital-detail' department.hid.hid %}">{{ department.hid.hname }}</a></td>
        </tr>
        {% endfor  %}
    </tbody>
</table>

{% else %}
<p>No resuorce are available.</p>
{% endif %}
{% endblock content %}

hospital/templates/hospital.html
{% extends './base.html' %}
{% block title %} Hostpital Management System
{% endblock title %}


{% block page_title %} {{ hospital.hname }}{% endblock  %}

{% block page_details %}
<div class="col-md-6 offset-md-3">
  <table class="table table-borderless table-sm">
    <thead>
      <tr>
        {% block details_title %}
        <th scope="col">Address</th>
        <th scope="col">City</th>
        <th scope="col">State</th>
        <th scope="col">Zipcode</th>
        {% endblock  %}
      </tr>
    </thead>
    <tbody>
      <tr>
        {% block details_content %}
        <td>{{ hospital.hst_address }}</td>
        <td>{{ hospital.hst_city }}</td>
        <td>{{ hospital.hstate }}</td>
        <td>{{ hospital.hzip }}</td>
        {% endblock  %}
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

{% block content %}


<div class="col-md-6 offset-md-3">
  <table class="table table-borderless table-sm">
    <tbody>
      <td>
      <th scope="row"> Number of Physician</th>
      <td>{{ hospital.physician_set.count }}</td>
      </td>
      <td>
        {% if  hospital.physician_set.count %}
        <a href="{% url 'hospital-physician' hospital.hid %}" class="badge badge-info">List of all Physicians</a>
        {% endif %}
      </td>
    </tbody>
  </table>
</div>


<h2>All Department</h2>
{% if hospital.department_set %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Department Name</th>
      <th scope="col">Telphone</th>
      {% if user.is_authenticated %}
      <th></th>
      {% endif %}

    </tr>
  </thead>
  <tbody>
    {% for department in hospital.department_set.all %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td onclick="window.location='{% url 'department-detail' department.did %}';">{{department.dname}}</td>
      <td>{{department.dtel}}</td>
      {% if user.is_authenticated %}
      <td><button type="button" class="btn btn-danger" data-toggle="modal"
          data-target="#modal_delete_{{ forloop.counter }}"><i class="fa fa-trash-o" aria-hidden="true"></i>
          Delete</button>
        <div id="modal_delete_{{ forloop.counter }}" class="modal fade" tabindex="-1" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Are you sure to delete {{department.dname}}?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{% url 'department-delete' department.did %}" method="post">
                  {% csrf_token %}
                  <input type="submit" type="button" class="btn btn-danger" value="Delete" />
                </form>
              </div>
            </div>
          </div>
        </div>
      </td>
      {% endif %}

    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>No resuorce are available.</p>
{% endif %}
<a href="{% url 'hospitals' %}" class="badge badge-info float-right">List of all Hostpital</a>
</br>
{% if user.is_authenticated %}
<button type="button" class="btn btn-success" data-toggle="modal" data-target="#addModal">
  <i class="fa fa-plus-circle"></i> Add new department
</button>
{% endif %}

<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add new department</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'department-add' hospital.hid %}" method="post">
          {% csrf_token %}
          {% for field in add_form %}
          <div class="form-group">
            {{ field.errors }}

            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
          </div>
          {% endfor %}
          <input type="submit" class="btn btn-primary" value="Submit">
        </form>

      </div>

    </div>
  </div>
</div>





{% endblock content %}

hospital/templates/index.html
{% extends './base.html' %}
{% block title %} Hostpital Management System
{% endblock title %}

{% block content %}



{% if hospital %}
<a href="{% url 'hospitals' %}">
    <h2> All Hostpitals </h2>
</a>
<ul class="list-group">
    {% for h in hospital %}
    <li class="list-group-item"><a href="{% url 'hospital-detail' h.hid %}">{{ h.hname }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No resuorce are available.</p>
{% endif %}
{% endblock content %}